#Requires -Version 5.1
# webbetonglammau - ENV SYNC Local -> Webhook -> Vercel
# ASCII-only script (safe for Windows PowerShell 5.1 encoding).
# Run via SETUP-ENV-LOCAL.bat (auto Admin).

[CmdletBinding()]
param(
  [string]$ConfigPath = '',
  [switch]$SkipWebhook,
  [switch]$Force
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

function Test-IsAdmin {
  $id = [Security.Principal.WindowsIdentity]::GetCurrent()
  $p = New-Object Security.Principal.WindowsPrincipal($id)
  return $p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

if (-not (Test-IsAdmin)) {
  Write-Host '[!] Chua co quyen Administrator - dang xin nang quyen...' -ForegroundColor Yellow
  $argList = @(
    '-NoProfile',
    '-ExecutionPolicy', 'Bypass',
    '-File', ('"{0}"' -f $PSCommandPath)
  )
  if ($ConfigPath) {
    $argList += @('-ConfigPath', ('"{0}"' -f $ConfigPath))
  }
  if ($SkipWebhook) { $argList += '-SkipWebhook' }
  if ($Force) { $argList += '-Force' }

  Start-Process -FilePath 'powershell.exe' -Verb RunAs -ArgumentList $argList -Wait
  exit $LASTEXITCODE
}

Write-Host ''
Write-Host '==============================================================' -ForegroundColor Cyan
Write-Host ' webbetonglammau - ENV SYNC LOCAL -> WEBHOOK -> VERCEL' -ForegroundColor Cyan
Write-Host ' Module 1 - PowerShell Administrator - KHONG qua Elmony' -ForegroundColor Cyan
Write-Host '==============================================================' -ForegroundColor Cyan
Write-Host ''

function Find-ProjectRoot {
  $parentOfScript = Split-Path -Parent $PSScriptRoot
  $grandParent = Split-Path -Parent $parentOfScript
  $candidates = @(
    $grandParent,
    $parentOfScript,
    $PSScriptRoot,
    (Get-Location).Path,
    'D:\SUPPER APP TRIEU DO\webbetonglammau'
  )

  foreach ($c in $candidates) {
    if ([string]::IsNullOrWhiteSpace($c)) { continue }
    $envEx = Join-Path $c '.env.example'
    $pkg = Join-Path $c 'package.json'
    if ((Test-Path -LiteralPath $envEx) -and (Test-Path -LiteralPath $pkg)) {
      return (Resolve-Path -LiteralPath $c).Path
    }
  }

  $dir = $PSScriptRoot
  for ($i = 0; $i -lt 6; $i++) {
    $envEx = Join-Path $dir '.env.example'
    if (Test-Path -LiteralPath $envEx) {
      return (Resolve-Path -LiteralPath $dir).Path
    }
    $parent = Split-Path -Parent $dir
    if ([string]::IsNullOrWhiteSpace($parent) -or ($parent -eq $dir)) { break }
    $dir = $parent
  }

  throw 'Khong tim thay thu muc goc du an (thieu .env.example + package.json).'
}

function Parse-EnvFile {
  param([Parameter(Mandatory = $true)][string]$Path)

  $map = [ordered]@{}
  $lines = Get-Content -LiteralPath $Path -Encoding UTF8
  foreach ($raw in $lines) {
    $line = $raw.Trim()
    if ([string]::IsNullOrWhiteSpace($line)) { continue }
    if ($line.StartsWith('#')) { continue }

    $idx = $line.IndexOf('=')
    if ($idx -lt 1) { continue }

    $key = $line.Substring(0, $idx).Trim()
    $val = $line.Substring($idx + 1).Trim()

    if ($val.Length -ge 2) {
      $q1 = $val.StartsWith('"') -and $val.EndsWith('"')
      $q2 = $val.StartsWith("'") -and $val.EndsWith("'")
      if ($q1 -or $q2) {
        $val = $val.Substring(1, $val.Length - 2)
      }
    }

    $map[$key] = $val
  }
  return $map
}

function New-ComplexSecret {
  param([int]$Length = 32)

  $alphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*-_=+'
  $bytes = New-Object byte[] $Length
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  try {
    $rng.GetBytes($bytes)
  }
  finally {
    $rng.Dispose()
  }

  $chars = New-Object char[] $Length
  for ($i = 0; $i -lt $Length; $i++) {
    $chars[$i] = $alphabet[$bytes[$i] % $alphabet.Length]
  }
  return (-join $chars)
}

function ConvertFrom-SecureStringPlain {
  param([Parameter(Mandatory = $true)][Security.SecureString]$Secure)

  $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($Secure)
  try {
    return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)
  }
  finally {
    [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
  }
}

function Write-EnvLocal {
  param(
    [Parameter(Mandatory = $true)][string]$Path,
    [Parameter(Mandatory = $true)][hashtable]$Values
  )

  $stamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
  $lines = @(
    '# ============================================================',
    '# .env.local - auto generated by SETUP-ENV-LOCAL.ps1',
    ('# Generated: {0}' -f $stamp),
    '# DO NOT commit this file to Git.',
    '# ============================================================',
    '',
    '# Supabase - public (RLS protected)',
    ('NEXT_PUBLIC_SUPABASE_URL={0}' -f $Values['NEXT_PUBLIC_SUPABASE_URL']),
    ('NEXT_PUBLIC_SUPABASE_ANON_KEY={0}' -f $Values['NEXT_PUBLIC_SUPABASE_ANON_KEY']),
    '',
    '# Supabase - SECRET (server-only)',
    ('SUPABASE_SERVICE_KEY={0}' -f $Values['SUPABASE_SERVICE_KEY']),
    ('SUPABASE_BUCKET={0}' -f $Values['SUPABASE_BUCKET']),
    '',
    '# Auth admin JWT',
    ('JWT_SECRET={0}' -f $Values['JWT_SECRET']),
    '',
    '# Public site URL',
    ('NEXT_PUBLIC_SITE_URL={0}' -f $Values['NEXT_PUBLIC_SITE_URL']),
    ''
  )

  $utf8NoBom = New-Object System.Text.UTF8Encoding $false
  [System.IO.File]::WriteAllLines($Path, $lines, $utf8NoBom)
}

# --- Resolve project root ---
$ProjectRoot = Find-ProjectRoot
Write-Host ('[1/7] Project root: {0}' -f $ProjectRoot) -ForegroundColor Green

$EnvExample = Join-Path $ProjectRoot '.env.example'
$EnvLocal = Join-Path $ProjectRoot '.env.local'
$ScriptDir = $PSScriptRoot

if ([string]::IsNullOrWhiteSpace($ConfigPath)) {
  $ConfigPath = Join-Path $ScriptDir 'env-sync.config.json'
}
$configExample = Join-Path $ScriptDir 'env-sync.config.example.json'

$config = @{
  webhookUrl        = ''
  webhookProvider   = 'make'
  vercelProjectName = 'webbetonglammau'
  vercelProjectId   = ''
  siteUrl           = 'https://webbetonglammau.vercel.app'
  supabaseBucket    = 'uploads'
  skipWebhook       = $false
}

if (Test-Path -LiteralPath $ConfigPath) {
  $raw = Get-Content -LiteralPath $ConfigPath -Raw -Encoding UTF8 | ConvertFrom-Json
  foreach ($p in $raw.PSObject.Properties) {
    if ($null -ne $p.Value -and ("{0}" -f $p.Value) -ne '') {
      $config[$p.Name] = $p.Value
    }
  }
  Write-Host ('[*] Da nap config: {0}' -f $ConfigPath) -ForegroundColor DarkGray
}
elseif (Test-Path -LiteralPath $configExample) {
  Write-Host '[!] Chua co env-sync.config.json - copy tu example...' -ForegroundColor Yellow
  Copy-Item -LiteralPath $configExample -Destination $ConfigPath -Force
  Write-Host '    Mo file, dan webhookUrl (Make/n8n), roi chay lai neu can ban cloud.' -ForegroundColor Yellow
}

if ($SkipWebhook) { $config.skipWebhook = $true }

$exampleMap = Parse-EnvFile -Path $EnvExample
Write-Host ('[2/7] Da doc .env.example ({0} bien)' -f $exampleMap.Count) -ForegroundColor Green

$requiredFromExample = @(
  'NEXT_PUBLIC_SUPABASE_URL',
  'NEXT_PUBLIC_SUPABASE_ANON_KEY'
)
foreach ($k in $requiredFromExample) {
  $hasKey = $exampleMap.Keys -contains $k
  if (-not $hasKey -or [string]::IsNullOrWhiteSpace([string]$exampleMap[$k])) {
    throw ('Thieu hoac trong bien bat buoc trong .env.example: {0}' -f $k)
  }
}

# --- Copy / init .env.local ---
if ((Test-Path -LiteralPath $EnvLocal) -and (-not $Force)) {
  Write-Host '[3/7] .env.local da ton tai - se ghi de cac truong quan trong.' -ForegroundColor Yellow
}
else {
  Copy-Item -LiteralPath $EnvExample -Destination $EnvLocal -Force
  Write-Host '[3/7] Da copy .env.example -> .env.local' -ForegroundColor Green
}

# --- Generate JWT_SECRET ---
$jwtSecret = New-ComplexSecret -Length 32
Write-Host '[4/7] Da sinh JWT_SECRET (32 ky tu)' -ForegroundColor Green

# --- Secure input SERVICE_KEY ---
Write-Host ''
Write-Host '[5/7] Nhap SUPABASE_SERVICE_KEY (service_role secret)' -ForegroundColor Cyan
Write-Host '     Lay tai: https://supabase.com/dashboard/project/bfruxinvvvaqufghtigw/settings/api' -ForegroundColor DarkGray
Write-Host '     Key bat dau bang eyJ... hoac sb_secret_... (khong hien khi go).' -ForegroundColor DarkGray
Write-Host ''

$secureKey = Read-Host -AsSecureString 'Dan SUPABASE_SERVICE_KEY roi Enter'
$serviceKey = ConvertFrom-SecureStringPlain -Secure $secureKey

if ([string]::IsNullOrWhiteSpace($serviceKey)) {
  throw 'SUPABASE_SERVICE_KEY trong - dung lai.'
}
if ($serviceKey -eq 'your_service_role_key_here') {
  throw 'Ban dang dan placeholder - can key service_role THAT tu Supabase.'
}
if ($serviceKey.Length -lt 20) {
  throw ('SUPABASE_SERVICE_KEY qua ngan ({0} ky tu) - kiem tra lai.' -f $serviceKey.Length)
}

$secureKey = $null

# --- Write .env.local ---
$bucket = 'uploads'
if ($config.supabaseBucket) { $bucket = [string]$config.supabaseBucket }
if (($exampleMap.Keys -contains 'SUPABASE_BUCKET') -and $exampleMap['SUPABASE_BUCKET']) {
  $bucket = [string]$exampleMap['SUPABASE_BUCKET']
}

$siteUrl = 'https://webbetonglammau.vercel.app'
if ($config.siteUrl) { $siteUrl = [string]$config.siteUrl }
if (($exampleMap.Keys -contains 'NEXT_PUBLIC_SITE_URL') -and $exampleMap['NEXT_PUBLIC_SITE_URL']) {
  $siteUrl = [string]$exampleMap['NEXT_PUBLIC_SITE_URL']
}

$final = @{
  'NEXT_PUBLIC_SUPABASE_URL'      = [string]$exampleMap['NEXT_PUBLIC_SUPABASE_URL']
  'NEXT_PUBLIC_SUPABASE_ANON_KEY' = [string]$exampleMap['NEXT_PUBLIC_SUPABASE_ANON_KEY']
  'SUPABASE_SERVICE_KEY'          = $serviceKey
  'SUPABASE_BUCKET'               = $bucket
  'JWT_SECRET'                    = $jwtSecret
  'NEXT_PUBLIC_SITE_URL'          = $siteUrl
}

Write-EnvLocal -Path $EnvLocal -Values $final
Write-Host '[6/7] Da ghi .env.local (UTF-8 no BOM)' -ForegroundColor Green

# --- Webhook payload ---
$envList = @(
  @{ key = 'NEXT_PUBLIC_SUPABASE_URL'; value = $final['NEXT_PUBLIC_SUPABASE_URL']; type = 'plain'; secret = $false },
  @{ key = 'NEXT_PUBLIC_SUPABASE_ANON_KEY'; value = $final['NEXT_PUBLIC_SUPABASE_ANON_KEY']; type = 'plain'; secret = $false },
  @{ key = 'SUPABASE_SERVICE_KEY'; value = $final['SUPABASE_SERVICE_KEY']; type = 'encrypted'; secret = $true },
  @{ key = 'SUPABASE_BUCKET'; value = $final['SUPABASE_BUCKET']; type = 'plain'; secret = $false },
  @{ key = 'JWT_SECRET'; value = $final['JWT_SECRET']; type = 'encrypted'; secret = $true },
  @{ key = 'NEXT_PUBLIC_SITE_URL'; value = $final['NEXT_PUBLIC_SITE_URL']; type = 'plain'; secret = $false }
)

$payload = [ordered]@{
  source                        = 'webbetonglammau-powershell'
  timestamp                     = (Get-Date).ToUniversalTime().ToString('o')
  vercelProjectName             = $config.vercelProjectName
  vercelProjectId               = $config.vercelProjectId
  environments                  = $envList
  NEXT_PUBLIC_SUPABASE_URL      = $final['NEXT_PUBLIC_SUPABASE_URL']
  NEXT_PUBLIC_SUPABASE_ANON_KEY = $final['NEXT_PUBLIC_SUPABASE_ANON_KEY']
  SUPABASE_SERVICE_KEY          = $final['SUPABASE_SERVICE_KEY']
  SUPABASE_BUCKET               = $final['SUPABASE_BUCKET']
  JWT_SECRET                    = $final['JWT_SECRET']
  NEXT_PUBLIC_SITE_URL          = $final['NEXT_PUBLIC_SITE_URL']
  targets                       = @('production', 'preview', 'development')
  action                        = 'upsert_env_and_redeploy'
}

$debugEnv = @()
foreach ($e in $envList) {
  $val = $e.value
  if ($e.secret) { $val = '***REDACTED***' }
  $debugEnv += @{ key = $e.key; value = $val; type = $e.type; secret = [bool]$e.secret }
}

$debugPayload = [ordered]@{
  source                        = $payload.source
  timestamp                     = $payload.timestamp
  vercelProjectName             = $payload.vercelProjectName
  vercelProjectId               = $payload.vercelProjectId
  environments                  = $debugEnv
  NEXT_PUBLIC_SUPABASE_URL      = $payload.NEXT_PUBLIC_SUPABASE_URL
  NEXT_PUBLIC_SUPABASE_ANON_KEY = $payload.NEXT_PUBLIC_SUPABASE_ANON_KEY
  SUPABASE_SERVICE_KEY          = '***REDACTED***'
  SUPABASE_BUCKET               = $payload.SUPABASE_BUCKET
  JWT_SECRET                    = '***REDACTED***'
  NEXT_PUBLIC_SITE_URL          = $payload.NEXT_PUBLIC_SITE_URL
  targets                       = $payload.targets
  action                        = $payload.action
}

$debugName = 'last-webhook-payload.{0:yyyyMMdd_HHmmss}.redacted.json' -f (Get-Date)
$debugPath = Join-Path $ScriptDir $debugName
($debugPayload | ConvertTo-Json -Depth 6) | Set-Content -LiteralPath $debugPath -Encoding UTF8
Write-Host ('     Debug payload (redacted): {0}' -f $debugPath) -ForegroundColor DarkGray

$wh = [string]$config.webhookUrl
$skipWh = [bool]$config.skipWebhook
$whPlaceholder = ($wh -match 'XXXX')

if ($skipWh -or [string]::IsNullOrWhiteSpace($wh) -or $whPlaceholder) {
  Write-Host '[7/7] BO QUA Webhook (chua cau hinh webhookUrl hoac -SkipWebhook).' -ForegroundColor Yellow
  Write-Host '     Sua scripts/env-sync/env-sync.config.json -> webhookUrl roi chay lai.' -ForegroundColor Yellow
}
else {
  Write-Host ('[7/7] Dang POST toi Webhook ({0})...' -f $config.webhookProvider) -ForegroundColor Cyan
  try {
    $bodyJson = $payload | ConvertTo-Json -Depth 8 -Compress
    $response = Invoke-RestMethod -Method Post -Uri $wh `
      -ContentType 'application/json; charset=utf-8' `
      -Body $bodyJson `
      -TimeoutSec 60

    Write-Host '     OK - Webhook thanh cong' -ForegroundColor Green
    if ($null -ne $response) {
      $respText = $response | ConvertTo-Json -Compress -Depth 4
      Write-Host ('     Response: {0}' -f $respText) -ForegroundColor DarkGray
    }
  }
  catch {
    Write-Host ('     LOI Webhook: {0}' -f $_.Exception.Message) -ForegroundColor Red
    Write-Host '     .env.local VAN da ghi xong - co the sync Vercel thu cong.' -ForegroundColor Yellow
    throw
  }
}

$serviceKey = $null
$final['SUPABASE_SERVICE_KEY'] = $null
$payload = $null
[GC]::Collect()

Write-Host ''
Write-Host '==============================================================' -ForegroundColor Green
Write-Host ' HOAN TAT MODULE 1' -ForegroundColor Green
Write-Host ('  Local:  {0}' -f $EnvLocal) -ForegroundColor Green
Write-Host '  Cloud:  Webhook -> Make/n8n -> Vercel API (Module 2)' -ForegroundColor Green
Write-Host '  Verify: chay 03_VERIFY_STORAGE.sql + PING-VERCEL-ADMIN.cmd' -ForegroundColor Green
Write-Host '==============================================================' -ForegroundColor Green
Write-Host ''
Write-Host 'Buoc tiep: npm run dev -> thu http://localhost:3000/admin' -ForegroundColor Cyan
Write-Host 'Nhan Enter de dong...' -ForegroundColor DarkGray
[void][Console]::ReadLine()
exit 0
